import spotipy
from datetime import date


def __create_Playlist(user_id: str, vibe: Vibe, source_content: str, playlist_name: str = ""):
    sp = spotipy.Spotify()

    if playlist_name != "":
        playlist_name = __generate_playlist_name(vibe, source_content)

    sp.user_create_playlist(user_id, playlist_name,
                            "Playlist generated by Ambiance on " + date.today().strftime("%B %d, %Y"))


def __generate_playlist_name(vibe: Vibe, source_content: str):
    if vibe == Vibe.PARTY:
        return "Ambiance Party Playlist: Day of " + date.today().strftime("%B %d, %Y")
    elif vibe == Vibe.PLAYLIST:
        return "Ambiance Playlist Based on the " + source_content + " Playlist"
    elif vibe == Vibe.SONG:
        return "Ambiance Playlist Based on " + source_content